USE ai_study_assistant;

CREATE TABLE tb_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tb_user
    ADD COLUMN password VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'BCrypt加密后的密码',
    ADD COLUMN avatar VARCHAR(500) DEFAULT NULL COMMENT '头像地址',
    ADD COLUMN role VARCHAR(20) DEFAULT 'User' COMMENT '角色',
    ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;